### ISSUE TITLE
label shape

### ISSUE THREAD

**Issue by emresar** [0xnurl/keras_character_based_ner#2]
Hello and thanks for the nice paper and work!
I have one question regarding the label shape. You note that the labels should be of shape (batch_size, num_labels), but shouldn't there be a label for each character in an input sentence of length sentence_maxlen? In that case shouldnt the labels be of shape (batch_size, num_labels, sentence_maxlen)?

**Comment by 0xnurl** [comment]
You are correct, the right shape is (batch_size, sentence_maxlen, num_labels). Will fix in documentation. Thanks!
